-- Local development seed: ~16 representative rows covering every rule the views and
-- search encode. Never run against production (the worker owns mirror.catalogue there).

insert into mirror.catalogue (
  airtable_record_id, airtable_modified_at, sku, product_name, brand, supplier, supplier_sku, ls_handle, collection,
  product_type, category, material_type, species, colour_tone, grade, width_in, length, thickness_mm, wear_layer_mil, veneer_mm,
  finish_type, install_profile, install_method, locking_system, underpad_included, underpad_type,
  cost, retail_price, map_price, promo_cost, promo_end_date, last_price_update, price_last_changed_by,
  box_size_sf, pieces_per_box, boxes_per_skid, stock_status, active,
  waterproof, pet_friendly, radiant_heat_compatible, traffic_rating, suitable_rooms, certifications,
  residential_warranty_yrs, salesperson_notes, pairs_well_with, internal_notes,
  undertone, tone_depth, texture, style, busyness, style_tags_status
) values
-- Vidar Macaroon: three grades sharing one LS handle → variant group. Character on promo.
('recVIDR0100C', now(), 'ENG-VIDR-0100C', 'Vidar 7.5" AWO — Macaroon (Character)', 'Vidar', 'VIDAR', null, 'VIDR75AWOMACAROON', '7.5 Collection',
 'Flooring', 'Engineered hardwood', 'Hardwood plywood', 'American White Oak', 'Light', 'Character', 7.5, '72"', 14.0, null, 3.0,
 'Wire brushed', 'T&G', 'Nail + glue assist', null, false, null,
 4.79, 5.79, null, 4.29, (now() at time zone 'America/Toronto')::date + 20, current_date - 10, 'Agent',
 23.31, 8, 40, null, true,
 false, false, true, 'Heavy residential', '{Bedroom,"Living room"}', '{Floorscore}',
 35, 'Best seller. Pairs with the matching stair nosing.', 'ACC-VIDR-0007, ACC-VIDR-0012', 'Ordered monthly.',
 'Warm', 2, 'Brushed', '{Modern,Scandinavian}', 'Moderate', 'Staff confirmed'),
('recVIDR0100S', now(), 'ENG-VIDR-0100S', 'Vidar 7.5" AWO — Macaroon (Select)', 'Vidar', 'VIDAR', null, 'VIDR75AWOMACAROON', '7.5 Collection',
 'Flooring', 'Engineered hardwood', 'Hardwood plywood', 'American White Oak', 'Light', 'Select', 7.5, '72"', 14.0, null, 3.0,
 'Wire brushed', 'T&G', 'Nail + glue assist', null, false, null,
 5.49, 6.49, null, null, null, current_date - 120, 'Manual',
 23.31, 8, 40, null, true,
 false, false, true, 'Heavy residential', '{Bedroom,"Living room"}', '{Floorscore}',
 35, null, null, null,
 'Warm', 2, 'Brushed', '{Modern,Scandinavian}', 'Calm', 'AI suggested'),
-- Rustic grade: expired promo, discontinued → hidden from public
('recVIDR0100R', now(), 'ENG-VIDR-0100R', 'Vidar 7.5" AWO — Macaroon (Rustic)', 'Vidar', 'VIDAR', null, 'VIDR75AWOMACAROON', '7.5 Collection',
 'Flooring', 'Engineered hardwood', 'Hardwood plywood', 'American White Oak', 'Light', 'Rustic', 7.5, '72"', 14.0, null, 3.0,
 'Wire brushed', 'T&G', 'Nail + glue assist', null, false, null,
 3.99, 4.99, null, 3.49, current_date - 5, current_date - 30, 'Agent',
 23.31, 8, 40, 'Discontinued', true,
 false, false, false, 'Heavy residential', '{Bedroom}', '{}',
 35, null, null, null,
 null, null, null, '{}', null, null),
-- Vidar 6" click, open-ended promo (no end date) → promo_active false, promo_open_ended true
('recVIDR0200', now(), 'ENG-VIDR-0200', 'Vidar 6" EWO — Whistler (Select & Better)', 'Vidar', 'VIDAR', null, 'VIDR6EWOWHISTLER', 'Click Collection',
 'Flooring', 'Engineered hardwood', 'Hardwood plywood', 'European White Oak', 'Natural', 'Select & Better', 6.0, '48"', 12.7, null, 2.0,
 'Matte UV', 'Click', 'Float', 'Valinge 5G', false, null,
 4.29, 5.29, null, 3.99, null, current_date - 200, 'Agent',
 20.10, 10, 48, null, true,
 false, false, true, 'Moderate residential', '{Bedroom,Condo}', '{Floorscore,"CARB II"}',
 25, null, null, null,
 'Neutral', 2, 'Smooth', '{Scandinavian,Coastal}', 'Calm', 'AI suggested'),
-- Biyork: MSRP stored in MAP, higher than retail. Public price must stay 3.63.
('recBIYK0001', now(), 'LVP-BIYK-BYKHYDRO7WI', 'Biyork Hydrogen 7 — Winter Fog', 'Biyork', 'BIYORK', 'BYKHYDRO7WI', 'BIYKLVPHYDRO7WINTERFOG', 'Hydrogen 7',
 'Flooring', 'LVP', 'SPC core', null, 'Grey', null, 7.0, '48"', 7.0, 20, null,
 'Embossed', 'Click', 'Float', 'I4F', true, 'IXPE',
 2.63, 3.63, 4.99, null, null, current_date - 3, 'Agent',
 23.64, 10, 60, 'In stock', true,
 true, true, true, 'Light commercial', '{Kitchen,Bathroom,Basement,Condo}', '{Floorscore}',
 30, null, null, null,
 'Cool', 3, 'Smooth', '{Modern}', 'Calm', 'Staff confirmed'),
-- Grandeur SPC 6" click, waterproof, pet friendly: the "6in click on promo" target
('recGRAN0001', now(), 'GRNDSPC-0001', 'Grandeur Enduro 6" SPC — Harbour Grey', 'Grandeur', 'GRANDEUR', 'GR-EN-HG6', 'GRNDSPCHARBOURGREY', 'Enduro',
 'Flooring', 'LVP', 'SPC core', null, 'Grey', null, 6.0, '48"', 6.5, 20, null,
 'Embossed', 'Click', 'Float', 'Valinge 2G', true, 'IXPE',
 2.19, 3.19, 3.49, 1.99, (now() at time zone 'America/Toronto')::date + 5, current_date - 1, 'Agent',
 23.64, 10, 60, null, true,
 true, true, true, 'Light commercial', '{Kitchen,Bathroom,Basement}', '{Floorscore}',
 25, null, null, null,
 'Cool', 3, 'Smooth', '{Modern,Coastal}', 'Calm', 'AI suggested'),
-- Canadian Standard distributing BOEN: supplier ≠ brand (search_staff-only term)
('recCANS0001', now(), 'ENG-CANS-0001', 'BOEN Chaletino 12" Oak — Vintage White', 'BOEN', 'CANADIAN STANDARD', 'CS-CH-VW', 'CANSENG12OAKVINTAGEWHITE', 'Chaletino',
 'Flooring', 'Engineered hardwood', 'Hardwood plywood', 'European White Oak', 'White', 'Character', 12.0, '86"', 20.0, null, 4.0,
 'Live Natural oil', 'T&G', 'Nail + glue assist', null, false, null,
 9.90, 10.90, null, null, null, current_date - 40, 'Manual',
 22.50, 4, 30, 'Special order', true,
 false, false, true, 'Heavy residential', '{"Living room"}', '{FSC}',
 25, null, null, null,
 'Neutral', 1, 'Brushed', '{Scandinavian,Traditional}', 'Busy', 'AI suggested'),
-- FAW laminate "Coming Soon"
('recFAWK0001', now(), 'LAM-FAWK-0042', 'NAF 12mm Waterproof Laminate 7.71" — Harrison', 'NAF', 'FLOORS AT WORK', null, 'FAWKLAMWPHARRISON', 'Waterproof Laminate',
 'Flooring', 'Laminate', 'Water-Resistant Core', null, 'Medium', null, 7.71, '48"', 12.0, null, null,
 'Embossed', 'Click', 'Float', 'Drop Click', true, null,
 1.99, 2.99, null, null, null, current_date - 8, 'Agent',
 20.25, 8, 56, null, true,
 true, false, false, 'Moderate residential', '{Kitchen,Bedroom}', '{}',
 20, 'COMING SOON — not yet in stock. Landing late October.', null, null,
 null, null, null, '{}', null, null),
-- Inactive (archived) Vidar — staff only
('recVIDR0182', now(), 'ENG-VIDR-0182', 'Vidar 7" AWO — Macaroon (Character) DUPLICATE', 'Vidar', 'VIDAR', null, 'VIDR7AWOMACAROON', '7 Collection',
 'Flooring', 'Engineered hardwood', 'Hardwood plywood', 'American White Oak', 'Light', 'Character', 7.0, '72"', 14.0, null, 3.0,
 'Wire brushed', 'T&G', 'Nail + glue assist', null, false, null,
 4.79, 5.79, null, null, null, null, 'Manual',
 23.31, 8, 40, null, false,
 false, false, true, 'Heavy residential', '{}', '{}',
 35, 'Archived: duplicate of ENG-VIDR-0100C', null, 'Archive after confirming.',
 null, null, null, '{}', null, null),
-- CIF STONE threshold: retail 0 by rule → price_on_request, per piece
('recCIFD0501', now(), 'STN-CIFD-0501', 'Threshold — Bianco Cararra — 3 x 36 x 3/8', 'CIF Distributors', 'CIF DISTRIBUTORS', null, 'CIFDSTNTHRESHOLDBIANCOCARARRA', 'Marble Thresholds',
 'Flooring', 'STONE', 'Marble', null, 'Bianco Cararra', null, 3.0, '36"', 9.5, null, null,
 'Polished', null, null, null, false, null,
 21.60, 0, null, null, null, current_date - 60, 'Manual',
 null, 10, null, null, true,
 false, false, false, null, '{Bathroom}', '{}',
 null, 'Origin: Italy', null, null,
 null, null, null, '{}', null, null),
-- CIF tile: two sizes of one colour share a handle, no grade → variant_label from size
('recCIFD0101', now(), 'TIL-CIFD-0101', 'Aldo — Bianco — 12 x 24 (Matte)', 'CIF Distributors', 'CIF DISTRIBUTORS', null, 'CIFDALDOBIANCO', 'Aldo',
 'Flooring', 'Tile / Stone', 'Porcelain', null, 'Bianco', null, 12.0, '24"', null, null, null,
 'Matte', null, null, null, false, null,
 2.39, 4.39, null, null, null, current_date - 15, 'Agent',
 15.50, 8, 40, null, true,
 false, false, false, null, '{Kitchen,Bathroom}', '{}',
 null, 'Origin: Spain', null, null,
 null, null, null, '{}', null, null),
('recCIFD0102', now(), 'TIL-CIFD-0102', 'Aldo — Bianco — 24 x 24 (Matte)', 'CIF Distributors', 'CIF DISTRIBUTORS', null, 'CIFDALDOBIANCO', 'Aldo',
 'Flooring', 'Tile / Stone', 'Porcelain', null, 'Bianco', null, 24.0, '24"', null, null, null,
 'Matte', null, null, null, false, null,
 2.79, 4.79, null, null, null, current_date - 15, 'Agent',
 15.75, 4, 40, 'Clearance', true,
 false, false, false, null, '{Kitchen,Bathroom}', '{}',
 null, 'Origin: Spain', null, null,
 null, null, null, '{}', null, null),
-- Olympia SKU with dots (stock code as SKU)
('recOLYM0001', now(), 'ES.AC.WHT.0416.VR.G', 'Aspen — White — 4 x 16 (Glossy)', 'Olympia Tile', 'OLYMPIA TILE', 'ES.AC.WHT.0416.VR.G', 'OLYMASPENWHITEGLOSSY', 'Aspen',
 'Flooring', 'Tile / Stone', 'Ceramic', null, 'White', null, 4.0, '16"', null, null, null,
 'Glossy', null, null, null, false, null,
 3.03, 5.03, null, null, null, current_date - 2, 'Agent',
 10.76, 24, 60, 'Low stock', true,
 false, false, false, null, '{Bathroom,Kitchen}', '{}',
 null, null, null, null,
 null, null, null, '{}', null, null),
-- Accessories referenced by pairs_well_with (per piece)
('recVIDRACC07', now(), 'ACC-VIDR-0007', 'Vidar - Transition | Stair Nosing | AWO | 94.5" Square', 'Vidar', 'VIDAR', null, 'VIDRACCNOSINGAWO', 'Accessories',
 'Accessory', 'Engineered hardwood', 'Hardwood plywood', 'American White Oak', null, null, null, '94.5"', null, null, null,
 null, null, null, null, false, null,
 38.00, 53.00, null, null, null, current_date - 10, 'Agent',
 null, 1, null, null, true,
 false, false, false, null, '{}', '{}',
 null, null, null, null,
 null, null, null, '{}', null, null),
('recVIDRACC12', now(), 'ACC-VIDR-0012', 'Vidar - Sundry | Underpad | 3mm IXPE 200sf Roll', 'Vidar', 'VIDAR', null, 'VIDRSUNDRYUNDERPAD3MM', 'Accessories',
 'Underpad', 'Engineered hardwood', null, null, null, null, null, null, 3.0, null, null,
 null, null, null, null, false, null,
 6.00, 26.00, null, null, null, current_date - 10, 'Agent',
 null, 1, null, 'Discontinued', true,
 false, false, false, null, '{}', '{}',
 null, null, null, null,
 null, null, null, '{}', null, null),
-- Woden looselay, pet friendly, glue-free
('recWODN0001', now(), 'LVP-WODN-0033', 'Woden 5mm Looselay 7.4" — 605', 'Woden', 'WODEN', null, 'WODNLVPLL605', '5mm Looselay Collection',
 'Flooring', 'LVP', 'Loose-lay vinyl', null, 'Medium', null, 7.4, '48"', 5.0, 20, null,
 'Embossed', 'Loose lay', 'Loose lay', null, false, null,
 2.49, 3.49, null, null, null, current_date - 100, 'Agent',
 24.86, 10, 50, null, true,
 true, true, false, 'Light commercial', '{Basement,Commercial}', '{}',
 15, null, null, null,
 'Warm', 4, 'Smooth', '{Traditional}', 'Moderate', 'AI suggested');

-- Images for the hero SKU: one swatch (low-res), one room scene, one detail; plus one soft-deleted.
insert into mirror.catalogue_images (
  airtable_record_id, sku, kind, airtable_attachment_id, sort_order, source_hash, original_path, original_mime, original_bytes,
  original_width, original_height, master_jpg_path, low_res, variant_paths, width, height, blurhash, encoder_version, public_base_url, deleted_at
) values
('recVIDR0100C', 'ENG-VIDR-0100C', 'swatch', 'attSW1', 0, repeat('a', 64), 'ENG-VIDR-0100C/' || repeat('a', 64) || '.jpg', 'image/jpeg', 812345,
 2400, 1600, null, false,
 jsonb_build_object('200', jsonb_build_object('path', 'ENG-VIDR-0100C/' || repeat('a', 64) || '_200.webp', 'w', 200, 'h', 133),
                    '600', jsonb_build_object('path', 'ENG-VIDR-0100C/' || repeat('a', 64) || '_600.webp', 'w', 600, 'h', 400),
                    '1600', jsonb_build_object('path', 'ENG-VIDR-0100C/' || repeat('a', 64) || '_1600.webp', 'w', 1600, 'h', 1067)),
 1600, 1067, 'LEHV6nWB2yk8pyo0adR*.7kCMdnj', 1, 'http://127.0.0.1:54321/storage/v1/object/public/catalogue-images', null),
('recVIDR0100C', 'ENG-VIDR-0100C', 'room', 'attRM1', 0, repeat('b', 64), 'ENG-VIDR-0100C/' || repeat('b', 64) || '.heic', 'image/heic', 3123456,
 4032, 3024, 'ENG-VIDR-0100C/' || repeat('b', 64) || '_master.jpg', false,
 jsonb_build_object('200', jsonb_build_object('path', 'ENG-VIDR-0100C/' || repeat('b', 64) || '_200.webp', 'w', 200, 'h', 150),
                    '600', jsonb_build_object('path', 'ENG-VIDR-0100C/' || repeat('b', 64) || '_600.webp', 'w', 600, 'h', 450),
                    '1600', jsonb_build_object('path', 'ENG-VIDR-0100C/' || repeat('b', 64) || '_1600.webp', 'w', 1600, 'h', 1200)),
 1600, 1200, 'L6PZfSi_.AyE_3t7t7R**0o#DgR4', 1, 'http://127.0.0.1:54321/storage/v1/object/public/catalogue-images', null),
('recVIDR0100C', 'ENG-VIDR-0100C', 'detail', 'attDT1', 0, repeat('c', 64), 'ENG-VIDR-0100C/' || repeat('c', 64) || '.png', 'image/png', 412345,
 800, 800, null, true,
 jsonb_build_object('200', jsonb_build_object('path', 'ENG-VIDR-0100C/' || repeat('c', 64) || '_200.webp', 'w', 200, 'h', 200),
                    '600', jsonb_build_object('path', 'ENG-VIDR-0100C/' || repeat('c', 64) || '_600.webp', 'w', 600, 'h', 600),
                    '1600', jsonb_build_object('path', 'ENG-VIDR-0100C/' || repeat('c', 64) || '_1600.webp', 'w', 800, 'h', 800)),
 800, 800, 'L5H2EC=PM+yV0g-mq.wG9c010J}I', 1, 'http://127.0.0.1:54321/storage/v1/object/public/catalogue-images', null),
('recVIDR0100C', 'ENG-VIDR-0100C', 'detail', 'attDT9', 1, repeat('d', 64), 'ENG-VIDR-0100C/' || repeat('d', 64) || '.jpg', 'image/jpeg', 99999,
 1200, 900, null, true,
 jsonb_build_object('200', jsonb_build_object('path', 'ENG-VIDR-0100C/' || repeat('d', 64) || '_200.webp', 'w', 200, 'h', 150)),
 1200, 900, null, 1, 'http://127.0.0.1:54321/storage/v1/object/public/catalogue-images', now() - interval '40 days'),
-- Grandeur has only a room scene → it becomes the hero
('recGRAN0001', 'GRNDSPC-0001', 'room', 'attRM2', 0, repeat('e', 64), 'GRNDSPC-0001/' || repeat('e', 64) || '.jpg', 'image/jpeg', 2222222,
 3000, 2000, null, false,
 jsonb_build_object('200', jsonb_build_object('path', 'GRNDSPC-0001/' || repeat('e', 64) || '_200.webp', 'w', 200, 'h', 133),
                    '600', jsonb_build_object('path', 'GRNDSPC-0001/' || repeat('e', 64) || '_600.webp', 'w', 600, 'h', 400),
                    '1600', jsonb_build_object('path', 'GRNDSPC-0001/' || repeat('e', 64) || '_1600.webp', 'w', 1600, 'h', 1067)),
 1600, 1067, 'LKO2?U%2Tw=w]~RBVZRi};RPxuwH', 1, 'http://127.0.0.1:54321/storage/v1/object/public/catalogue-images', null);

-- A finished sync run so sync_status has something to show locally.
insert into mirror.sync_runs (mode, trigger, started_at, finished_at, status, fetched, inserted, updated, deleted, issues, api_calls)
values ('full', 'seed', now() - interval '20 minutes', now() - interval '19 minutes', 'success', 16, 16, 0, 0, 0, 1);
